### ISSUE TITLE
user-can-create-an-account

### ISSUE THREAD

**Issue by Andrew-M-A** [Andrew-M-A/AJAX-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account and begin to track their macronutrients

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive form that will generate a user's account and their respective macronutrient totals to track

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-14 at 10 19 28 AM](https://user-images.githubusercontent.com/99862668/173638246-93d26ca0-0f23-40dc-8b26-9fd14282a4bd.png)

![Screen Shot 2022-06-14 at 10 20 35 AM](https://user-images.githubusercontent.com/99862668/173638423-1ea8c2d0-92bf-46ab-814e-f50dbfcb3ec9.png)

![Screen Shot 2022-06-14 at 10 21 24 AM](https://user-images.githubusercontent.com/99862668/173638575-6cf82105-6e31-48a9-8bc6-3cff34382c45.png)

![Screen Shot 2022-06-14 at 10 35 29 AM](https://user-images.githubusercontent.com/99862668/173641056-c82eb6a0-bccc-4c4d-929d-fe5c387b0a47.png)

![Screen Shot 2022-06-14 at 10 36 07 AM](https://user-images.githubusercontent.com/99862668/173641181-d251241c-1684-4ce9-8b86-2259b18c2dee.png)

![Screen Shot 2022-06-14 at 10 36 51 AM](https://user-images.githubusercontent.com/99862668/173641245-ded265b2-2b51-4bb7-88e9-b315ca4386f0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a [data-view=profile] div to the html
- [ ] Create a form within the [data-view=profile] div
- [ ] Make sure that all inputs are highlighted when clicked on
- [ ] Make sure that the "Feet" and "Inches" inputs have appropriate limits
- [ ] Make sure that the "Activity Level" dropdown has a "Light Activity," "Moderate Activity," and "Heavy Activity" option
- [ ] Make sure that the "Goals" dropdown has a "Maintain," "Gain," and "Lose" option
- [ ] Add a 'submit' event listener to the form
- [ ] Generate a new object to hold the input values when form is submitted
- [ ] Calculate caloric and macro (carbs, proteins, fats) totals to track based on user's info
- [ ] Ensure that user profile page has all input values and macros displayed
- [ ] Ensure that the user interface looks natural on both mobile and desktop screens.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs and all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all functionality works without errors.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
